package tokobuku;

public enum Kota {
	SURABAYA, JAKARTA, BANDUNG,
	SIDOARJO, PASURUAN, GRESIK,
	BONDOWOSO, PURWOKERTO, KEDIRI,
	BEKASI, DEPOK, YOGYAKARTA,
	SEMARANG, BALI, BANYUWANGI,
	BALIKPAPAN, SAMARINDA, JAYAPURA,
	BATAM, LAMPUNG, PADANG
}
